#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <unistd.h>
#include <sys/mman.h>
#include <sys/types.h>
#include <sys/wait.h>
#include "./fractal.h"
#include "./image.h"
#include <sys/stat.h>
#include <fcntl.h>

/*
    generate and save the entire fractal
    returns:    0 if successful
                1 otherwise
*/
int generate_fractal(char *file, float width, float height, int workers) {
    /*  TODO: use fork(), mmap(), and munmap() to create a region of shared memory
            to store fractal data, as generated by several child processes  */

    int status = 0;
    off_t offset = 0;
    int out_fd;

    // open file
    if((out_fd = open(file, O_APPEND | O_RDWR | O_CREAT, 0600)) == -1) {
      printf("Could not open destination file\n");
      exit(1);
    }

    // create region of memory
    size_t filesize = sizeof(color_t) * width * height;
    color_t* fractal_data = mmap(NULL, filesize, PROT_READ | PROT_WRITE, MAP_SHARED | MAP_ANONYMOUS, out_fd, offset);

    pid_t pid;
    pid_t children[workers];

    for(int i = 0; i < workers; i++) {
      if(!(pid = fork())) {
        generate_fractal_region(fractal_data, width, height, offset, height/workers);
        save_image_data(file, fractal_data, width, height);
        munmap(fractal_data, filesize);
        exit(0);
      }

      offset += height/workers;
      children[i] = pid;
    }

    // wait for child processes to finish
    for(int i = 0; i < workers; i++) {
      waitpid(children[i], &status, 0);
    }

    munmap(fractal_data, filesize);
    printf("Complete \n");
    return 0;
}
